"""World map of firm counts by country, hatched by the prevalent treatment
category. `run(sample, group)` for one cell of the grid."""
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import matplotlib.patheffects as pe
from shapely.geometry import MultiPolygon

try:
    from . import fig_common as fc
except ImportError:
    import fig_common as fc

# naturalearth_lowres codes these as "-99"
ISO_FIX = {"France": "FRA", "Norway": "NOR", "Kosovo": "XKX", "Somaliland": "SOM", "N. Cyprus": "CYP"}
RED, BLUE, GREY = "#FF0000", "#0000FF", "#f0f0f0"
HATCH = {"nbr1": "ooooo", "nbr2": "xxxxx", "distant": "/////"}
EDGE = {"nbr1": RED, "nbr2": RED, "distant": BLUE}


def _world():
    try:
        world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
    except AttributeError:  # geopandas >= 1.0 removed the bundled datasets
        import geodatasets
        world = gpd.read_file(geodatasets.get_path("naturalearth.land"))
    if "iso_a3" not in world.columns:
        raise RuntimeError("World layer has no iso_a3 column.")
    world = world.rename(columns={"iso_a3": "iso3"})
    fix = world["name"].map(ISO_FIX)
    world.loc[(world["iso3"] == "-99") & fix.notna(), "iso3"] = fix
    return world


def _country_table(df):
    """One row per FIRM (not firm-day), then counts per country."""
    firms = df.drop_duplicates("ric")[["ric", "ctriso3", "nbr_1", "nbr_1_or_2"]].copy()
    firms["nbr_2"] = ((firms["nbr_1"] == 0) & (firms["nbr_1_or_2"] == 1)).astype(int)
    firms["dist"] = ((firms["nbr_1"] == 0) & (firms["nbr_1_or_2"] == 0)).astype(int)
    country = firms.groupby("ctriso3").agg(n_firms=("ric", "nunique"), n_nbr1=("nbr_1", "sum"),
                                           n_nbr2=("nbr_2", "sum"), n_dist=("dist", "sum")).reset_index()
    country = country.rename(columns={"ctriso3": "iso3"})

    def classify(r):
        if r["n_nbr1"] > r["n_nbr2"] and r["n_nbr1"] > r["n_dist"]:
            return "nbr1"
        if r["n_nbr2"] > r["n_nbr1"] and r["n_nbr2"] > r["n_dist"]:
            return "nbr2"
        return "distant"
    country["cat"] = country.apply(classify, axis=1)
    return country


def _country_name(iso3):
    try:
        import pycountry
        c = pycountry.countries.get(alpha_3=iso3)
        return (c.common_name if hasattr(c, "common_name") else c.name) if c else iso3
    except Exception:
        return iso3


def _country_tex(country: pd.DataFrame, path, sample: str, group: str):
    """Appendix table: Country | ISO3 | Firms | 1st-degree | 2nd-degree | Distant, in three
    blocks (first-degree, second-degree, distant countries), firms descending, total row."""
    t = country.copy()
    t["name"] = t["iso3"].map(_country_name).str.replace("&", "\\&")
    blocks = [("First-degree neighbors of Ukraine", t[t["n_nbr1"] > 0]),
              ("Second-degree neighbors of Ukraine", t[(t["n_nbr1"] == 0) & (t["n_nbr2"] > 0)]),
              ("Distant countries", t[(t["n_nbr1"] == 0) & (t["n_nbr2"] == 0)])]
    L = ["% Generated by analysis/src/d01_figures/fig_descriptives_core.py - do not edit by hand",
         "\\begin{table}[htbp]\\centering",
         f"\\caption{{\\textbf{{Firms by Country}} \\\\ Number of firms in the {'matched ' if group == 'matched' else ''}"
         f"{'main' if sample == 'main' else 'balanced'} sample by headquarters country and proximity to Ukraine.}}",
         f"\\label{{tab:countries_{sample}_{group}}}", "\\begin{adjustbox}{max height=0.9\\textheight}",
         "\\begin{tabular}{llrrrr}", "\\toprule",
         "Country & ISO3 & Firms & 1st-degree & 2nd-degree & Distant \\\\ \\midrule"]
    for title, b in blocks:
        if b.empty:
            continue
        L.append(f"\\multicolumn{{6}}{{l}}{{\\textit{{{title}}}}} \\\\")
        for _, r in b.sort_values(["n_firms", "name"], ascending=[False, True]).iterrows():
            L.append(f"{r['name']} & {r['iso3']} & {int(r['n_firms']):,} & {int(r['n_nbr1']):,} & {int(r['n_nbr2']):,} & {int(r['n_dist']):,} \\\\")
        L.append("\\addlinespace")
    L.append(f"\\midrule Total & & {int(t['n_firms'].sum()):,} & {int(t['n_nbr1'].sum()):,} & {int(t['n_nbr2'].sum()):,} & {int(t['n_dist'].sum()):,} \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{adjustbox}", "\\end{table}"]
    Path(path).write_text("\n".join(L) + "\n")


def _centroid(geom):
    if isinstance(geom, MultiPolygon):
        geom = max(geom.geoms, key=lambda g: g.area)
    c = geom.centroid
    if not geom.contains(c):
        c = geom.representative_point()
    return c.x, c.y


def run(sample: str, group: str):
    out_dir = fc.out_dir("map", sample, group)
    df = fc.load_panel("daily", sample, ["ric", "ctriso3", "nbr_1", "nbr_1_or_2"])
    df = fc.assign_groups(df, group, "sample_label")
    df["ctriso3"] = df["ctriso3"].astype(str).str.upper()
    df = df[df["ctriso3"] != "NAN"]
    for c in ["nbr_1", "nbr_1_or_2"]:
        df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0).astype(int)

    country = _country_table(df)
    merged = _world().merge(country, on="iso3", how="left")
    merged["n_firms"] = merged["n_firms"].fillna(0)
    merged["cat"] = merged["cat"].fillna("none")

    plt.rcParams.update({"font.family": "serif", "font.size": 12, "axes.linewidth": 0.6, "figure.dpi": 300})
    fig, ax = plt.subplots(figsize=(14, 7))
    merged[merged["cat"] == "none"].plot(ax=ax, color=GREY, edgecolor="white", linewidth=0.3)
    for cat in ["nbr1", "nbr2", "distant"]:
        sub = merged[merged["cat"] == cat]
        if len(sub):
            sub.plot(ax=ax, facecolor="white", edgecolor=EDGE[cat], hatch=HATCH[cat], linewidth=0.35)
    placed = []
    for _, row in merged[merged["n_firms"] > 0].iterrows():
        try:
            x, y = _centroid(row.geometry)
        except Exception:
            continue
        for px, py in placed:
            if abs(px - x) < 0.4 and abs(py - y) < 0.4:
                x += 0.5; y += 0.5
        placed.append((x, y))
        ax.text(x, y, str(int(row["n_firms"])), ha="center", va="center", fontsize=5, color="white",
                fontweight="bold", path_effects=[pe.withStroke(linewidth=1, foreground="black")])
    ax.set_axis_off()
    ax.legend(handles=[Patch(facecolor="white", edgecolor=RED, hatch="ooooo", label="Nearby (1st-degree)"),
                       Patch(facecolor="white", edgecolor=RED, hatch="xxxxx", label="Nearby (2nd-degree)"),
                       Patch(facecolor="white", edgecolor=BLUE, hatch="/////", label="Distant"),
                       Patch(facecolor=GREY, edgecolor="black", label="No firms")],
              loc="lower left", frameon=True, facecolor="white", edgecolor="gray", fontsize=10)
    plt.tight_layout()
    plt.savefig(out_dir / "world_firms.png")
    plt.close(fig)
    tab_dir = fc.tab_dir("map", sample, group)
    country.to_csv(tab_dir / "firms_by_country.csv", index=False)
    if sample == "main":
        _country_tex(country, tab_dir / "firms_by_country.tex", sample, group)
    print(f"✅ map [{sample}|{group}] → {out_dir}")
