"""Build the paper's sample-selection material from analysis/output/sampling/sampling_log.csv
(plus the tick-filter counts and the overnight composition tables when present):
- analysis/output/tables/sample_selection.tex   : Table tab:sample in the manuscript's two-column "./" format
- analysis/output/tables/matching/balance.tex   : covariate balance before/after matching and entropy balancing
- docs/paper/sampling/data_section.tex          : Data section + Appendix B prose, numbers filled from the log
- docs/paper/sampling/formulas_appendix.tex     : variable definitions with the tick-filter counts filled in
- docs/paper/notes/filtering.md                 : the whole funnel in Markdown (successor of filtering.rtf)
Run after the pipeline (merge -> gathering -> matching -> figures)."""
import csv
import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[3]
LOG = ROOT / "analysis" / "output" / "sampling" / "sampling_log.csv"
PAPER = ROOT / "docs" / "paper"
OUT, NOTES = PAPER / "sampling", PAPER / "notes"          # hand-written templates -> generated text
TABLES = ROOT / "analysis" / "output" / "tables"          # generated tables (copied into the paper by hand)
TICK_COUNTS = ROOT / "preprocessing" / "data" / "02_preprocessed" / "trth" / "summary" / "tick_filter_counts.csv"
BALANCE = ROOT / "analysis" / "data" / "psm_balance.csv"
for d in (OUT, NOTES, TABLES / "matching"):
    d.mkdir(parents=True, exist_ok=True)

# tick-level universe from preprocessing/src/d01_preprocessing/trth_summary.py (not re-run)
TRTH = {"proximity_firms": 18681, "trth_rics": 18512, "rows": 11_176_354_771,
        "quotes": 9_344_665_205, "trades": 1_831_689_566}
# Datastream funnel of the manuscript (Appendix B / Table tab:sample); the pipeline starts from
# its last row. The penny-stock row is derived so that the funnel ends at the merge output
# (the rule is now the Datastream USD price only) and cross-checked against the merge log.
DATASTREAM_FUNNEL = [
    ("Firms with missing postal codes", 9222),
    ("Firms with postal codes we could not match with GeoNames", 14425),
    ("Firms with too many missing prices", 6075),
    ("Firms with missing tick history data", 169),
    ("Firms with data outside trading hours", 22),
    ("Firms with missing data on market value of equity or smaller than \\$10m", 1068),
    ("Firms with price at or below \\$1 (penny stocks) or a local price at or below 1", None),
    ("Listings quoted in a currency different from that of their exchange", "fx"),
    ("Firms in Aerospace and Defense sectors", 84),
    ("Firms from Russia or Ukraine", 79),
]
DATASTREAM_TOTAL = 48403


def fmt(x):
    return "" if x in ("", None) else f"{int(x):,}"


def load():
    with open(LOG, newline="") as f:
        return list(csv.DictReader(f))


def find(rows, stage, pattern):
    for r in rows:
        if r["stage"] == stage and re.search(pattern, r["step"]):
            return r
    raise KeyError(f"{stage}: /{pattern}/ not in sampling_log.csv")


def nearby(rows, cell):
    m = re.search(r"Nearby ([\d,]+)", find(rows, "figures_daily", "^" + re.escape(cell) + "$")["note"])
    return int(m.group(1).replace(",", ""))


def build_table(rows):
    g = lambda stage, pat, key="firms": int(find(rows, stage, pat)[key])
    main5, ds_win, d_main = g("merge", "^Main 5-minute"), g("gathering", "^daily: rows in window"), g("gathering", "^daily: main")
    i_main = g("gathering", "^intraday: main")
    pairs, unmatched = g("matching", "^Matched pairs"), g("matching", "without a control")
    fx_excl = g("merge", "currency different")
    penny = DATASTREAM_TOTAL - sum(n for _, n in DATASTREAM_FUNNEL if isinstance(n, int)) - fx_excl - main5
    penny_log = g("merge", "penny stocks")
    if abs(penny - penny_log) > 50:
        print(f"⚠️ penny-stock row derived from the funnel ({penny:,}) differs from the merge log ({penny_log:,})")
    funnel = [(lab, fx_excl if n == "fx" else (n if n else penny)) for lab, n in DATASTREAM_FUNNEL]
    L = ["% Generated by analysis/src/d03_docs/build_sampling_docs.py from sampling_log.csv - do not edit by hand",
         "\\begin{table}[htbp]\\centering",
         "\\caption{\\textbf{Firm Sample Selection} \\\\ Table outlines the initial firm sample obtained from Thomson Reuters Datastream "
         "and then merged with the LSEG tick history database and the number of firms dropped in each step of the sample selection.}",
         "\\begin{adjustbox}{max width=\\textwidth}", "\\label{tab:sample}", "\\begin{tabular}{lr}", "\\toprule",
         f"Total Firms & {fmt(DATASTREAM_TOTAL)} \\\\\\midrule", "\\addlinespace"]
    L += [f"./ {lab} & {fmt(n)} \\\\" for lab, n in funnel]
    L += ["\\midrule", f"Firms sample with intraday data in the event window & {fmt(main5)} \\\\",
          f"./ Firms without a trading day with all microstructure variables & {fmt(main5 - ds_win)} \\\\",
          f"./ Firms without data both before and after the invasion & {fmt(ds_win - d_main)} \\\\",
          "\\midrule",
          f"Firms sample with daily data surrounding event (main sample) & {fmt(d_main)} \\\\",
          f"Firms sample with first-/second-degree neighboring countries of Ukraine & {fmt(nearby(rows, 'main | full'))} \\\\",
          f"Firms sample with intraday data surrounding event & {fmt(i_main)} \\\\",
          f"Firms intraday sample with first-/second-degree neighboring countries of Ukraine & {fmt(_nearby_intra(rows))} \\\\",
          "\\midrule",
          f"Firms sample with matched pairs (Nearby firms with a Distant control) & {fmt(2 * pairs)} \\\\",
          f"./ Nearby firms without a control inside the caliper & {fmt(unmatched)} \\\\",
          "\\bottomrule", "\\end{tabular}", "\\end{adjustbox}", "\\end{table}"]
    return "\n".join(L) + "\n"


def _nearby_intra(rows):
    m = re.search(r"Nearby ([\d,]+)", find(rows, "figures_intraday", r"^main \| full$")["note"])
    return int(m.group(1).replace(",", ""))


def build_balance():
    if not BALANCE.exists():
        return
    b = pd.read_csv(BALANCE)
    L = ["% Generated by analysis/src/d03_docs/build_sampling_docs.py from analysis/data/psm_balance.csv",
         "\\begin{table}[htbp]\\centering",
         "\\caption{\\textbf{Covariate Balance} \\\\ Standardized mean differences (Nearby minus Distant) of the pre-invasion "
         "firm-level medians used to build the matched sample and the entropy-balancing weights.}",
         "\\label{tab:balance}", "\\begin{tabular}{llrr}", "\\toprule",
         "Method & Covariate & SMD before & SMD after \\\\ \\midrule"]
    lab = {"log(mktval)": "log market value", "log(dollar_volume_sum)": "log dollar volume",
           "log(qspread_mean)": "log quoted spread", "ps_logit": "logit propensity score"}
    for _, r in b.iterrows():
        meth = r["method"].replace("·", "$\\cdot$").replace("entropy_balancing", "entropy balancing")
        meth = meth[0].upper() + meth[1:]
        L.append(f"{meth} & {lab.get(r['variable'], r['variable'])} & {r['smd_before']:.3f} & {r['smd_after']:.3f} \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (TABLES / "matching" / "balance.tex").write_text("\n".join(L) + "\n")


def build_md(rows):
    L = ["# Sample selection (generated from `analysis/output/sampling/sampling_log.csv`)", ""]
    L.append("## Tick data (trth_summary)")
    L.append(f"- proximity file: {fmt(TRTH['proximity_firms'])} firms; covered in TRTH: {fmt(TRTH['trth_rics'])}")
    L.append(f"- tick records: {fmt(TRTH['rows'])} (quotes {fmt(TRTH['quotes'])}, trades {fmt(TRTH['trades'])})")
    if TICK_COUNTS.exists():
        t = pd.read_csv(TICK_COUNTS); t = t[t["file"] == "TOTAL"].iloc[0]
        L.append(f"- tick filters (counting pass over the Phase-1 shards): crossed quotes {fmt(t['crossed_quotes'])}, "
                 f"stub quotes {fmt(t['stub_quotes'])} ({t['stub_quotes_pct_of_quotes']:.3f}% of {fmt(t['quotes'])} quotes), "
                 f"negative price/volume {fmt(t['neg_price_or_volume'])}, bad prints {fmt(t['bad_prints'])} "
                 f"({t['bad_prints_pct_of_trades']:.4f}% of {fmt(t['trades'])} trades)")
    for stage in ["merge", "gathering", "matching", "figures_daily", "figures_intraday", "figures_overnight"]:
        sub = [r for r in rows if r["stage"] == stage]
        if not sub:
            continue
        L += ["", f"## {stage}", "", "| step | firms | rows | note |", "|---|---:|---:|---|"]
        for r in sub:
            L.append(f"| {r['step']} | {fmt(r['firms'])} | {fmt(r['rows'])} | {r['note']} |")
    return "\n".join(L) + "\n"


def values(rows):
    g = lambda stage, pat, key="firms": fmt(find(rows, stage, pat)[key])
    vals = {
        "TRTH_FIRMS": fmt(TRTH["trth_rics"]), "TRTH_ROWS": fmt(TRTH["rows"]),
        "MERGE_FIRMS_IN": g("merge", "^5-minute rows"), "MERGE_ROWS_IN": g("merge", "^5-minute rows", "rows"),
        "ROWS_NO_HOURS": g("merge", "without trading-hours", "rows"), "ROWS_OUT_HOURS": g("merge", "outside local", "rows"),
        "ROWS_WEEKEND": g("merge", "Saturdays", "rows"), "ROWS_HOLIDAY": g("merge", "holidays", "rows"),
        "FIRMS_DS": g("merge", "matched to Datastream"), "FIRMS_NXX": g("merge", "NXX"),
        "FIRMS_PENNY": g("merge", "penny"), "FIRMS_AERODEF": g("merge", "Aerospace"), "FIRMS_RUSUKR": g("merge", "Russian"),
        "FIRMS_FX": g("merge", "currency different"),
        "FIRMS_MAIN5": g("merge", "^Main 5-minute"), "ROWS_MAIN5": g("merge", "^Main 5-minute", "rows"),
        "ROWS_MAIN_DAILY": g("merge", "^Main daily", "rows"),
        "DAILY_MAIN_FIRMS": g("gathering", "^daily: main"), "DAILY_MAIN_ROWS": g("gathering", "^daily: main", "rows"),
        "DAILY_BAL_FIRMS": g("gathering", "^daily: balanced"), "DAILY_BAL_ROWS": g("gathering", "^daily: balanced", "rows"),
        "INTRA_MAIN_FIRMS": g("gathering", "^intraday: main"), "INTRA_MAIN_ROWS": g("gathering", "^intraday: main", "rows"),
        "INTRA_BAL_FIRMS": g("gathering", "^intraday: balanced"), "INTRA_BAL_ROWS": g("gathering", "^intraday: balanced", "rows"),
        "MATCH_VALID": g("matching", "valid pre-period"), "MATCH_PAIRS": g("matching", "^Matched pairs"),
        "MATCH_UNMATCHED": g("matching", "without a control"), "EB_ESS": g("matching", "effective number"),
        "MATCH_NOTE": find(rows, "matching", "^Matched pairs")["note"].replace("*", "$\\cdot$"),
        "MATCH_TC": find(rows, "matching", "valid pre-period")["note"],
    }
    for key, cell in [("NEARBY_MAIN", "main | full"), ("NEARBY_BAL", "balanced | full")]:
        try:
            vals[key] = fmt(nearby(rows, cell))
        except KeyError:
            pass
    try:
        note = find(rows, "figures_daily", r"^main \| full$")["note"]
        vals["DISTANT_MAIN"] = re.search(r"Distant ([\d,]+)", note).group(1)
    except KeyError:
        pass
    if TICK_COUNTS.exists():
        t = pd.read_csv(TICK_COUNTS); t = t[t["file"] == "TOTAL"].iloc[0]
        vals.update({"N_QUOTES": fmt(t["quotes"]), "N_TRADES": fmt(t["trades"]),
                     "N_CROSSED": fmt(t["crossed_quotes"]), "N_STUB": fmt(t["stub_quotes"]),
                     "PCT_STUB": f"{t['stub_quotes_pct_of_quotes']:.3f}\\%",
                     "N_NEGATIVE": fmt(t["neg_price_or_volume"]), "N_BADPRINT": fmt(t["bad_prints"]),
                     "PCT_BADPRINT": f"{t['bad_prints_pct_of_trades']:.4f}\\%"})
    for sfx, group in [("", "full"), ("_M", "matched")]:
        f = TABLES / "overnight" / "main" / group / "overnight_sample.csv"
        if f.exists():
            o = pd.read_csv(f).iloc[0]
            vals.update({f"OVN_FIRMS{sfx}": fmt(o["firms"]), f"OVN_EXCH{sfx}": fmt(o["exchanges"]),
                         f"OVN_CTRY{sfx}": fmt(o["countries"]) if pd.notna(o.get("countries")) else "?"})
    return vals


def fill(template: Path, dest: Path, vals):
    text = template.read_text()
    for k, v in vals.items():
        text = text.replace("{{" + k + "}}", str(v))
    left = sorted(set(re.findall(r"\{\{([A-Z_0-9]+)\}\}", text)))
    if left:
        print(f"⚠️ {dest.name}: unfilled placeholders {left}")
    dest.write_text(f"% Generated from {template.name} by build_sampling_docs.py\n" + text)


def main():
    rows = load()
    (TABLES / "sample_selection.tex").write_text(build_table(rows))
    (NOTES / "filtering.md").write_text(build_md(rows))
    build_balance()
    vals = values(rows)
    for stem in ("data_section", "formulas_appendix"):
        tpl = OUT / f"{stem}.template.tex"
        if tpl.exists():
            fill(tpl, OUT / f"{stem}.tex", vals)
    # the hand-written notes carry the same tick-filter placeholders: fill them in place once the counts exist
    notes = NOTES / "measures.md"
    if notes.exists() and "{{" in notes.read_text() and "N_STUB" in vals:
        text = notes.read_text()
        for k, v in vals.items():
            text = text.replace("{{" + k + "}}", str(v).replace("\\%", "%"))
        notes.write_text(text)
    print("✅ analysis/output/tables/{sample_selection,matching/balance}.tex, docs/paper/sampling/{data_section,formulas_appendix}.tex, docs/paper/notes/filtering.md")


if __name__ == "__main__":
    main()
